### ISSUE TITLE
URLSearchParams accepts an object in the constructor

### ISSUE THREAD

**Issue by vkrol** [travishorn/searchparamify#1]
Hello!

The current version of `URLSearchParams` accepts an object in the constructor.
Proof: https://codesandbox.io/s/urlsearchparams-object-tdo8i.
The corresponding change in the specification was made on 11 Jan 2017: https://github.com/whatwg/url/pull/175#issuecomment-271828734.

**Comment by travishorn** [comment]
I looks like it has decent browser support, too.
https://caniuse.com/#feat=mdn-api_urlsearchparams_urlsearchparams

Thanks. Archiving this project.
